# Generated by Django 4.0.2 on 2023-05-08 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_booksearch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookSearch',
            new_name='ProductSearch',
        ),
    ]
